name: Bug Report
description: Create a bug report
labels: ["bug"]
assignees:
  - hycrafthd
body:
  - type: input
    id: bug_description
    attributes:
      label: Bug desciption
      description: "What happened and what is the issue"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true
