name: Bug Report
description: Create a bug report
labels: ["bug"]
assignees:
  - hycrafthd
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug description and reproduction steps
      description: "What is not working correctly and how can we trigger this bug"
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
